language: node_js
node_js:
  - "0.8"

install:
  - "cd .."
  - "ls -l"
  - "git clone git://github.com/xtuple/xtuple.git --recursive"
  - "cd xtuple"
  - "bash scripts/install_xtuple.sh -ipn"
  - "./scripts/build_app.js -d dev -e ../xtuple-extensions/source/time_expense"
  - "cp test/lib/login_data.js ../xtuple-extensions/test/lib/login_data.js"

before_script:
  - "cd ../xtuple-extensions"
  - "npm install"
  - "cd ../xtuple/node-datasource"
  - "node main.js &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test"
  - "npm run-script test-datasource"
  - "cd ../xtuple-extensions"
  - "npm run-script test"
